on: [pull_request]

env:
  PNPM_VERSION: 9.1.2

jobs:
  prettier:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    name: prettier
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: pnpm install
      - name: Check formatting
        run: pnpm format:check

  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: pnpm install
      - name: Build Vitepress
        run: pnpm build
